### ISSUE TITLE
2.15 Open issue sheet

### ISSUE THREAD

**Issue by qwksilver** [Geektoolkit/Dynaframe3#59]
From #45 
- [ ] #8 b : Misc File Formats to still be addressed (WEBM, GIF)
- [ ] #18  : Advanced idea, can it add blurboxing effect to blank space in uniform mode
- [ ] #45 : Add other options for not shuffled playlist sorting, currently only supporting filename
- [ ] #48 : Add COMITUP functionality for AP direct access for initial setup of wifi or direct access to frame outside network
- [ ] #53 : rc.local investigation and improved bootup
- [x] #52 : Settings menu streamlining
New
- [ ] #59 : Live log view

**Comment by qwksilver** [comment]
through an off-git conversation we've devised a plan to implement a way to view the log in realtime, possibly with a pause command, or autoscroll command, to be able to watch the logging from the web interface, this is strictly for debuging purposes, and will likely be a hidden tab.

**Comment by qwksilver** [comment]
Closing and moving to #83
